-- FOOD (category_id = 1, id 1–50)
-- DRINKS (category_id = 2, id 51–64)
-- DESSERT (category_id = 3, id 65–78)

INSERT INTO menu (menu_id, name, category_id, price, image) VALUES
(1, 'rice_plain', 1, 10.00, 'src-front/img-oneDishMeal/kaosuay.png'),
(2, 'kapow_moosub', 1, 45.00, 'src-front/img-oneDishMeal/padkrapaomoosap.avif'),
(3, 'kapow_moodeng', 1, 55.00, 'src-front/img-oneDishMeal/moodeng.jpg'),
(4, 'kapow_squid', 1, 70.00, 'src-front/img-oneDishMeal/kapowpamuk.webp'),
(5, 'kapow_moogrob', 1, 60.00, 'src-front/img-oneDishMeal/kapowmukob.webp'),
(6, 'kapow_gai', 1, 50.00, 'src-front/img-oneDishMeal/kapowgai.webp'),
(7, 'kapowkung', 1, 65.00, 'src-front/img-oneDishMeal/kapowkung.jpg'),
(8, 'prikgaeng_pork', 1, 45.00, 'src-front/img-oneDishMeal/prikkang moo.jpg'),
(9, 'prikgaeng_chicken', 1, 50.00, 'src-front/img-oneDishMeal/prikkang gai.webp'),
(10, 'prikgaeng_beef', 1, 60.00, 'src-front/img-oneDishMeal/prikkang beef.webp'),
(11, 'kana_moogrob', 1, 60.00, 'src-front/img-oneDishMeal/kanamukob.jpg'),
(12, 'khaenang_moogrob', 1, 55.00, 'src-front/img-oneDishMeal/kanangmukob.jpg'),
(13, 'morning_glory', 1, 45.00, 'src-front/img-oneDishMeal/padpakbung.jpeg'),
(14, 'mixed_veg', 1, 50.00, 'src-front/img-oneDishMeal/padpakruam.jpg'),
(15, 'curry_squid', 1, 70.00, 'src-front/img-oneDishMeal/pongkaree pamuk.jpg'),
(16, 'curry_shrimp', 1, 65.00, 'src-front/img-oneDishMeal/pongkaree kung.jpg'),
(17, 'curry_chicken', 1, 55.00, 'src-front/img-oneDishMeal/pongkaree gai.jpg'),
(18, 'garlic_pork', 1, 45.00, 'src-front/img-oneDishMeal/moo kateam.jpg'),
(19, 'garlic_chicken', 1, 50.00, 'src-front/img-oneDishMeal/gai kateam.jpg'),
(20, 'oyster_pork', 1, 45.00, 'src-front/img-oneDishMeal/moo nammanhoi.jpg'),
(21, 'chilipork_caps', 1, 50.00, 'src-front/img-oneDishMeal/moo pikyuak.jpg'),
(22, 'chilichicken_caps', 1, 55.00, 'src-front/img-oneDishMeal/gai prikyuak.jpg'),
(23, 'sweet_sour_pork', 1, 55.00, 'src-front/img-oneDishMeal/preawwanmoo.jpg'),
(24, 'sweet_sour_fish', 1, 70.00, 'src-front/img-oneDishMeal/preawwanfish.webp'),
(25, 'kee_mao_pork', 1, 50.00, 'src-front/img-oneDishMeal/keemao moo.jpg'),
(26, 'kee_mao_chicken', 1, 55.00, 'src-front/img-oneDishMeal/keemao gai.jpg'),
(27, 'kee_mao_beef', 1, 65.00, 'src-front/img-oneDishMeal/keemao beef.jpg'),
(28, 'kee_mao_sea', 1, 75.00, 'src-front/img-oneDishMeal/keemao tale.png'),
(29, 'spaghetti_kee_mao', 1, 65.00, 'src-front/img-oneDishMeal/spa keemao.jpg'),
(30, 'kai_omelet_rice', 1, 35.00, 'src-front/img-oneDishMeal/kaokaijeaw.jpg'),
(31, 'omelet_shrimp', 1, 50.00, 'src-front/img-oneDishMeal/kaijeaw kung.jpg'),
(32, 'omelet_pork', 1, 45.00, 'src-front/img-oneDishMeal/kaijeaw moosub.jpg'),
(33, 'omelet_crab', 1, 80.00, 'src-front/img-oneDishMeal/kaijeaw poo.jpg'),
(34, 'fried_rice_pork', 1, 50.00, 'src-front/img-oneDishMeal/kaopad moo.jpg'),
(35, 'fried_rice_shrimp', 1, 65.00, 'src-front/img-oneDishMeal/kaopadkung.png'),
(36, 'fried_rice_sea', 1, 70.00, 'src-front/img-oneDishMeal/kaopad tale.jpg'),
(37, 'fried_rice_canned_fish', 1, 50.00, 'src-front/img-oneDishMeal/kaopad papong.webp'),
(38, 'pad_see_ew_pork', 1, 55.00, 'src-front/img-oneDishMeal/padsiew moo.jpg'),
(39, 'rad_na_pork', 1, 55.00, 'src-front/img-oneDishMeal/radna moo.webp'),
(40, 'pad_thai_shrimp', 1, 50.00, 'src-front/img-oneDishMeal/padthai kungsod.webp'),
(41, 'tom_jued_pork', 1, 50.00, 'src-front/img-oneDishMeal/tomjuad moo.webp'),
(42, 'suki_water_pork', 1, 55.00, 'src-front/img-oneDishMeal/sukinam moo.jpg'),
(43, 'suki_water_sea', 1, 70.00, 'src-front/img-oneDishMeal/sukinam tale.jpg'),
(44, 'suki_dry_porkู', 1, 55.00, 'src-front/img-oneDishMeal/suki hang moo.jpg'),
(45, 'yum_mu_yo', 1, 50.00, 'src-front/img-oneDishMeal/yum moo yor.jpg'),
(46, 'yum_woonsen_sea', 1, 70.00, 'src-front/img-oneDishMeal/yum wonsen tale.jpg'),
(47, 'yum_canned_fish', 1, 50.00, 'src-front/img-oneDishMeal/yum pakapong.jpg'),
(48, 'khao_tom_shrimp', 1, 65.00, 'src-front/img-oneDishMeal/kaotom kung.jpg'),
(49, 'khao_tom_pork', 1, 45.00, 'src-front/img-oneDishMeal/kaotom moosab.jpg'),
(50, 'khao_tom_fish', 1, 60.00, 'src-front/img-oneDishMeal/kaotom pla.jpg'),
(51, 'water', 2, 10.00, 'src-front/img-beverage/namthip.jpeg'),
(52, 'pepsi', 2, 25.00, 'src-front/img-beverage/pepsi.webp'),
(53, 'strawberry_soda', 2, 35.00, 'src-front/img-beverage/strawberry_lime_soda.jpg'),
(54, 'blue_hawaii_soda', 2, 35.00, 'src-front/img-beverage/blue_hawaii.jpg'),
(55, 'red_syrup_soda', 2, 35.00, 'src-front/img-beverage/red_soda.jpg'),
(56, 'peach_tea', 2, 35.00, 'src-front/img-beverage/peach_tea.jpg'),
(57, 'lychee_juice', 2, 35.00, 'src-front/img-beverage/lychee.webp'),
(58, 'lemon_tea', 2, 35.00, 'src-front/img-beverage/lemon_tea.jpg'),
(59, 'apple_tea', 2, 35.00, 'src-front/img-beverage/apple_tea.avif'),
(60, 'thai_tea', 2, 35.00, 'src-front/img-beverage/thai_tea.jpg'),
(61, 'green_tea', 2, 40.00, 'src-front/img-beverage/green_tea.webp'),
(62, 'oleang', 2, 40.00, 'src-front/img-beverage/oleang.webp'),
(63, 'ovaltine', 2, 35.00, 'src-front/img-beverage/ovaltine.jpg'),
(64, 'traditional_coffee', 2, 40.00, 'src-front/img-beverage/coffee.jpg'),
(65, 'nuggets', 3, 40.00, 'src-front/img-dessert/nugget.webp'),
(66, 'chicken_pop', 3, 40.00, 'src-front/img-dessert/pop-chicken.jpg'),
(67, 'french_fries', 3, 40.00, 'src-front/img-dessert/french-fries.jpg'),
(68, 'cheese_ball', 3, 50.00, 'src-front/img-dessert/cheese-ball.jpg'),
(69, 'fried_sausage', 3, 40.00, 'src-front/img-dessert/sausages.jpg'),
(70, 'mashed_potato_cheese_bake', 3, 65.00, 'src-front/img-dessert/potato.webp'),
(71, 'fried_chicken_wings', 3, 55.00, 'src-front/img-dessert/chicken-wings.jpg'),
(72, 'gyoza', 3, 60.00, 'src-front/img-dessert/dumpling.jpg'),
(73, 'toast', 3, 50.00, 'src-front/img-dessert/bread.jpg'),
(74, 'ice_cream', 3, 45.00, 'src-front/img-dessert/ice-cream.jpg'),
(75, 'lava_cake', 3, 70.00, 'src-front/img-dessert/choclava.jpg'),
(76, 'soft_cake', 3, 75.00, 'src-front/img-dessert/cake.jpg'),
(77, 'bua_loy', 3, 65.00, 'src-front/img-dessert/coconut-cream.webp'),
(78, 'pa_tong_go', 3, 65.00, 'src-front/img-dessert/patonggo.png');
